import { ExternalLink, MessageCircle, Quote, Star } from 'lucide-react';
import type { GeneralServicesContent } from './content';

export function CustomerReviews({ content }: { content: GeneralServicesContent }) {
  const { googleReviews: google, testimonials } = content;
  const hasRating = google.rating !== null && google.count !== null && google.count > 0;
  const badge = <><span className="google-review-brand"><span className="google-letter" aria-hidden="true">G</span>Google{google.url && <ExternalLink size={15} aria-hidden="true" />}</span>{hasRating ? <span className="google-review-score"><strong>{google.rating}/5</strong><span>{google.count} críticas</span></span> : <span className="google-review-score"><span>Avaliações de clientes</span></span>}</>;
  return <section className="customer-reviews section" id="depoimentos" aria-labelledby="reviews-title"><div className="shell">
    <div className="reviews-heading"><div><div className="kicker">A EXPERIÊNCIA DOS NOSSOS CLIENTES</div><h2 id="reviews-title">O cuidado nota-se.<br /><em>A sua opinião conta.</em></h2></div>{google.url ? <a className="google-review-badge" href={google.url} target="_blank" rel="noopener noreferrer" aria-label={hasRating ? `Google: ${google.rating} em 5, ${google.count} críticas. Abrir avaliações` : 'Ver avaliações no Google'}>{badge}</a> : hasRating ? <div className="google-review-badge">{badge}</div> : null}</div>
    {testimonials.length > 0 ? <div className="reviews-grid">{testimonials.map((review, index) => <figure className="review-card" key={`${review.author}-${index}`}><div className="review-card-top"><Quote size={28} aria-hidden="true" />{review.rating !== undefined && <span className="review-stars" aria-label={`${review.rating} em 5 estrelas`}>{Array.from({ length: 5 }, (_, i) => <Star key={i} size={16} fill={i < review.rating! ? 'currentColor' : 'none'} aria-hidden="true" />)}</span>}</div><blockquote>{review.quote}</blockquote><figcaption><span className="review-avatar" aria-hidden="true">{review.author.slice(0, 1)}</span><span><strong>{review.author}</strong>{review.date && <small>{review.date}</small>}</span>{review.url && <a href={review.url} target="_blank" rel="noopener noreferrer" aria-label={`Ler avaliação de ${review.author} no Google`}><ExternalLink size={18} aria-hidden="true" /></a>}</figcaption></figure>)}</div> : <div className="reviews-invitation"><MessageCircle size={30} aria-hidden="true" /><div><h3>Já recebeu a nossa equipa?</h3><p>Conte-nos como correu. A sua opinião ajuda-nos a cuidar cada vez melhor de cada espaço.</p></div><a className="button secondary" target="_blank" rel="noopener noreferrer" href={`https://wa.me/${content.whatsappNumber}?text=${encodeURIComponent('Olá! Gostaria de partilhar a minha experiência com a SofaClean.')}`}>Partilhar experiência <ExternalLink size={16} aria-hidden="true" /></a></div>}
    {hasRating && <p className="reviews-source">Excertos de avaliações publicadas no Google. Classificação consultada em {google.checkedOn}. <a href={google.url} target="_blank" rel="noopener noreferrer">Ver todas as críticas no Google <ExternalLink size={14} aria-hidden="true" /></a></p>}
  </div></section>;
}

