'use client';
import { useEffect, useState } from 'react';
import { X } from 'lucide-react';
type LegalKind = 'terms' | 'returns' | 'privacy';
const routes: Record<LegalKind,string> = { terms:'/sofaclean/termos-e-condicoes', returns:'/sofaclean/politica-de-devolucoes', privacy:'/sofaclean/privacidade' };
const titles: Record<LegalKind,string> = { terms:'Termos e Condições', returns:'Política de Devoluções', privacy:'Política de Privacidade' };
const fallbackContent: Record<LegalKind,string> = {
  terms: '<p><strong>Última atualização: setembro de 2026</strong></p><h2>1. Identificação</h2><p>A SofaClean presta serviços profissionais de limpeza e higienização de estofos ao domicílio nas regiões do Porto e Braga.</p><h2>2. Serviços e orçamentos</h2><p>Os orçamentos são gratuitos e o preço final é confirmado antes da marcação, de acordo com o artigo, dimensão e tratamento solicitado.</p><h2>3. Pagamento e cancelamento</h2><p>O pagamento é efetuado no final do serviço. Cancelamentos ou reagendamentos devem ser comunicados com pelo menos 24 horas.</p><h2>4. Reclamações</h2><p>Qualquer reclamação fundamentada deve ser comunicada até 48 horas após o serviço, para avaliação e eventual repetição da intervenção.</p>',
  returns: '<p>A SofaClean presta serviços personalizados de limpeza e higienização. Por se tratar de uma prestação de serviços, não existem devoluções após a conclusão da intervenção.</p><h2>Garantia de repetição</h2><p>Insatisfações fundamentadas comunicadas no prazo de 48 horas são avaliadas e, quando aplicável, a intervenção é repetida sem custos.</p><h2>Cancelamentos</h2><p>O cancelamento ou reagendamento deve ser comunicado com 24 horas de antecedência.</p>',
  privacy: '<p><strong>Última atualização: setembro de 2026</strong></p><h2>Contacto e âmbito</h2><p>Esta política aplica-se aos serviços da SofaClean no Porto e em Braga. Para questões sobre dados pessoais, contacte-nos através do email sofaclean.porto@gmail.com.</p><h2>Dados e finalidades</h2><p>Podemos recolher nome, telefone, email, localidade, fotografias e dados do serviço para responder a pedidos, preparar propostas e executar o serviço.</p><h2>Os seus direitos</h2><p>Pode solicitar acesso, retificação, apagamento, limitação ou oposição ao tratamento dos seus dados, nos termos do RGPD.</p>'
};
export function LegalModal({ kind, onClose }: { kind: LegalKind; onClose: () => void }) {
  const [html, setHtml] = useState('');
  useEffect(() => { let active = true; setHtml(fallbackContent[kind]); fetch(`${routes[kind]}?modal=1`, { headers: { Accept: 'text/html' } }).then(r => r.text()).then(text => { if (!active) return; const doc = new DOMParser().parseFromString(text, 'text/html'); const content = doc.querySelector('.legal-content') || doc.querySelector('main'); if (content?.innerHTML) setHtml(content.innerHTML); }).catch(() => undefined); return () => { active = false; }; }, [kind]);
  useEffect(() => { const key=(e:KeyboardEvent)=>e.key==='Escape'&&onClose(); document.addEventListener('keydown',key); const old=document.body.style.overflow; document.body.style.overflow='hidden'; return()=>{document.removeEventListener('keydown',key);document.body.style.overflow=old}; },[onClose]);
  return <div className="legal-modal-backdrop" role="presentation" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="legal-modal" role="dialog" aria-modal="true" aria-labelledby="legal-modal-title"><button className="legal-modal-close" type="button" onClick={onClose} aria-label="Fechar"><X size={22}/></button><h2 id="legal-modal-title" className="legal-modal-heading">{titles[kind]}</h2><div className="legal-modal-content">{html ? <div dangerouslySetInnerHTML={{__html: html}} /> : <p>A carregar conteúdo…</p>}</div></section></div>;
}
