'use client';
import { useEffect, useState } from 'react';
import { X } from 'lucide-react';
type LegalKind = 'terms' | 'returns' | 'privacy';
const routes: Record<LegalKind,string> = { terms:'/sofaclean/termos-e-condicoes', returns:'/sofaclean/politica-de-devolucoes', privacy:'/sofaclean/privacidade' };
const titles: Record<LegalKind,string> = { terms:'Termos e Condições', returns:'Política de Devoluções', privacy:'Política de Privacidade' };
const fallbackContent: Record<LegalKind,string> = {
  terms: '<p><strong>Última atualização: setembro de 2026</strong></p><h2>1. Identificação</h2><p>A SofaClean Porto presta serviços de limpeza, higienização e impermeabilização profissional de sofás, colchões, tapetes, cadeiras e outros estofos ao domicílio nas regiões do Porto e Braga.</p><h2>2. Orçamentos e reservas</h2><p>Os orçamentos iniciais são gratuitos e sem compromisso. O preço final é confirmado antes da marcação, considerando tipologia, dimensões, tratamentos e deslocação.</p><h2>3. Prestação do serviço</h2><p>O cliente deve assegurar acesso ao local, água e eletricidade funcionais. Os resultados dependem do estado, idade, composição e natureza da sujidade do artigo.</p><h2>4. Direito de livre resolução</h2><p>Nos termos do Decreto-Lei n.º 24/2014, o cliente solicita expressamente o início imediato da prestação e reconhece a perda do direito após a conclusão integral do serviço.</p><h2>5. Pagamento e cancelamento</h2><p>O pagamento é efetuado no final do serviço. Cancelamentos ou reagendamentos devem ser comunicados com pelo menos 24 horas.</p><h2>6. Reclamações e garantia</h2><p>Uma insatisfação fundamentada deve ser comunicada até 48 horas após o serviço. Validada a reclamação, a intervenção poderá ser repetida sem custos adicionais.</p><h2>7. Proteção de dados e lei aplicável</h2><p>O tratamento de dados cumpre o RGPD. Estes termos regem-se pela lei portuguesa e, em caso de litígio, é competente o tribunal da comarca do Porto.</p>',
  returns: '<p>A SofaClean Porto preza pela transparência, qualidade e rigor na prestação dos seus serviços de limpeza e higienização profissional de estofos.</p><h2>1. Natureza do serviço e resultados</h2><p>Por se tratar de uma prestação de serviços e não da venda de um produto físico, não se aplicam devoluções após a conclusão da intervenção. Os resultados dependem do tecido, idade, conservação e natureza da sujidade.</p><h2>2. Direito de livre resolução</h2><p>Ao confirmar o serviço, o cliente solicita expressamente o início imediato da execução e reconhece as limitações previstas no Decreto-Lei n.º 24/2014.</p><h2>3. Garantia de repetição</h2><p>Insatisfações fundamentadas comunicadas no prazo máximo de 48 horas são avaliadas. Quando validada, a intervenção é repetida sem custos adicionais.</p><h2>4. Cancelamentos</h2><p>O cancelamento ou reagendamento deve ser comunicado com 24 horas de antecedência. Ausências ou cancelamentos tardios podem implicar taxa de deslocação.</p><h2>5. Contactos</h2><p>WhatsApp e telefone: +351 920 320 174. Email: sofaclean.porto@gmail.com.</p>',
  privacy: '<p><strong>Última atualização: setembro de 2026</strong></p><h2>Contacto e âmbito</h2><p>Esta política aplica-se aos serviços da SofaClean no Porto e em Braga. Para questões sobre dados pessoais, contacte-nos através do email sofaclean.porto@gmail.com.</p><h2>Dados e finalidades</h2><p>Podemos recolher nome, telefone, email, localidade, fotografias e dados do serviço para responder a pedidos, preparar propostas e executar o serviço.</p><h2>Os seus direitos</h2><p>Pode solicitar acesso, retificação, apagamento, limitação ou oposição ao tratamento dos seus dados, nos termos do RGPD.</p>'
};
export function LegalModal({ kind, onClose }: { kind: LegalKind; onClose: () => void }) {
  const [html, setHtml] = useState('');
  useEffect(() => { let active = true; setHtml(fallbackContent[kind]); fetch(`${routes[kind]}?modal=1`, { headers: { Accept: 'text/html' } }).then(r => r.text()).then(text => { if (!active) return; const doc = new DOMParser().parseFromString(text, 'text/html'); const content = doc.querySelector('.legal-content') || doc.querySelector('main'); if (content?.innerHTML) setHtml(content.innerHTML); }).catch(() => undefined); return () => { active = false; }; }, [kind]);
  useEffect(() => { const key=(e:KeyboardEvent)=>e.key==='Escape'&&onClose(); document.addEventListener('keydown',key); const old=document.body.style.overflow; document.body.style.overflow='hidden'; return()=>{document.removeEventListener('keydown',key);document.body.style.overflow=old}; },[onClose]);
  return <div className="legal-modal-backdrop" role="presentation" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="legal-modal" role="dialog" aria-modal="true" aria-labelledby="legal-modal-title"><button className="legal-modal-close" type="button" onClick={onClose} aria-label="Fechar"><X size={22}/></button><h2 id="legal-modal-title" className="legal-modal-heading">{titles[kind]}</h2><div className="legal-modal-content">{html ? <div dangerouslySetInnerHTML={{__html: html}} /> : <p>A carregar conteúdo…</p>}</div></section></div>;
}
