import { LegalPage } from '@/sofaclean_site/LegalPage';
export const metadata = { title: 'Política de privacidade | SofaClean' };
export default function PrivacyPage() {
  return <LegalPage title="Política de privacidade">
    <h2>Contacto e âmbito</h2><p>Esta política descreve os contactos relacionados com os serviços da SofaClean no Porto e em Braga. Para questões sobre dados pessoais ou para exercer os seus direitos, contacte +351 920 320 174 por telefone ou WhatsApp. A identificação legal completa do responsável deve acompanhar os documentos de contratação.</p>
    <h2>Dados e finalidades</h2><p>Ao pedir um orçamento, pode fornecer nome, telefone, localidade, fotografias dos artigos e informação sobre o serviço. A morada é necessária quando se combina uma deslocação; os dados fiscais são solicitados para faturação quando aplicável. Evite enviar fotografias com pessoas, documentos ou outros dados desnecessários.</p><p>Estes dados permitem responder ao pedido, preparar a proposta e executar o serviço, com fundamento nas diligências pré-contratuais e no contrato. A faturação e outras exigências legais baseiam-se no cumprimento de obrigações legais. O uso de imagens para divulgação ou o envio de publicidade exige uma autorização separada, que pode ser retirada.</p>
    <h2>Conservação e acesso</h2><p>Os dados são conservados durante o tempo necessário ao pedido e ao serviço, bem como pelos períodos legalmente exigidos para documentos fiscais ou para a defesa de direitos. O acesso deve limitar-se a quem precisa dos dados para essas finalidades, incluindo prestadores de apoio sujeitos a deveres de confidencialidade e autoridades quando a lei o exigir.</p>
    <h2>Serviços externos</h2><p>Os links para WhatsApp, Instagram, Google Maps e Livro de Reclamações abrem serviços externos com políticas próprias. Os respetivos operadores podem tratar dados técnicos e de utilização, incluindo fora do Espaço Económico Europeu, segundo as suas condições e mecanismos de proteção. O site não envia automaticamente uma mensagem quando abre o WhatsApp.</p>
    <h2>Cookies e dados técnicos</h2><p>Esta página e a página SofaClean não incluem formulários, ferramentas de publicidade ou mapas incorporados. Não foi adicionada medição de audiência nem cookies de marketing. O alojamento pode processar dados técnicos, como endereço IP e registos de acesso, para disponibilizar e proteger o site. Uma futura introdução de tecnologias opcionais deverá ser acompanhada da informação e escolhas exigidas por lei.</p>
    <h2>Os seus direitos</h2><p>Nos termos aplicáveis, pode solicitar acesso, retificação, apagamento, limitação, portabilidade ou opor-se ao tratamento. Pode retirar o consentimento sem afetar o tratamento anterior. Apenas serão pedidos elementos de identificação proporcionais ao pedido. Pode apresentar uma reclamação à <a href="https://www.cnpd.pt/">Comissão Nacional de Proteção de Dados</a>. Saiba mais sobre os <a href="https://www.cnpd.pt/cidadaos/direitos/">direitos dos titulares</a>.</p>
  </LegalPage>;
}
